# =============================================================================
# DVC Pipeline for Hallucination Detection
# =============================================================================
# 目录结构: {base}/{dataset}/{model}/seed_{seed}/{task_type}/
# 
# 流程顺序:
#   1. split_dataset - 分割数据集
#   2. generate_activations - 提取训练集特征
#   3. generate_activations_test - 提取测试集特征
#   4. train_probe - 训练探测器
#   5. evaluate - 评估
#   6. aggregate - 汇总结果
# =============================================================================

vars:
  - params.yaml

stages:
  # ===========================================================================
  # Stage 1: 数据分割
  # ===========================================================================
  split_dataset:
    cmd: python scripts/split_dataset.py
    deps:
      - scripts/split_dataset.py
      - config/dataset/
    params:
      - datasets
      - split
      - seed
    outs:
      - outputs/splits/:
          persist: true

  # ===========================================================================
  # Stage 2a: 训练集特征提取
  # ===========================================================================
  generate_activations: 
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
    cmd: >-
      CUDA_VISIBLE_DEVICES=${cuda_devices}
      python scripts/generate_activations.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      dataset.split_name=train
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      features.mode=${features.mode}
      features.max_length=${features.max_length}
      features.batch_size=${features.batch_size}
      seed=${seed}
      methods=[${methods_str}]
      allow_full_attention=${allow_full_attention}
    deps:
      - scripts/generate_activations.py
      - src/
      - config/
      - utils/
      - outputs/splits/
    # 只追踪真正影响原始特征提取的参数
    # methods 和 allow_full_attention 不影响是否需要重新提取
    params:
      - features.mode
      - features.max_length
      - features.batch_size
      - seed
      - methods
    outs:
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/: 
          persist: true

  # ===========================================================================
  # Stage 2b: 测试集特征提取
  # ===========================================================================
  generate_activations_test: 
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
    cmd: >-
      CUDA_VISIBLE_DEVICES=${cuda_devices}
      python scripts/generate_activations.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      dataset.split_name=test
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      features.mode=${features.mode}
      features.max_length=${features.max_length}
      features.batch_size=${features.batch_size}
      seed=${seed}
      methods=[${methods_str}]
      allow_full_attention=${allow_full_attention}
    deps:
      - scripts/generate_activations.py
      - src/
      - config/
      - utils/
      - outputs/splits/
    # 追踪影响特征提取的参数（与训练集保持一致）
    params:
      - features.mode
      - features.max_length
      - features.batch_size
      - seed
      - methods
    outs:
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}_test/: 
          persist: true

  # ===========================================================================
  # Stage 3: 训练探测器
  # ===========================================================================
  train_probe: 
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
      method: ${methods}
    cmd: >-
      python scripts/train_probe.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      method=${item.method}
      seed=${seed}
    deps:
      - scripts/train_probe.py
      - src/
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/
      - outputs/splits/
    params:
      - seed
      - cv_folds
    outs:
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/probe/: 
          persist: true

  # ===========================================================================
  # Stage 4: 评估
  # ===========================================================================
  evaluate:
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
      method: ${methods}
    cmd: >-
      python scripts/evaluate.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      method=${item.method}
      seed=${seed}
    deps: 
      - scripts/evaluate.py
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/probe/
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}_test/
      - outputs/splits/
    params:
      - seed
    metrics:
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/eval_results.json:
          cache: false
    plots:
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/roc_curve.json:
          cache: false
          x: fpr
          y: tpr

  # ===========================================================================
  # Stage 5: 汇总结果
  # ===========================================================================
  aggregate:
    cmd: python scripts/aggregate_results.py
    deps:
      - scripts/aggregate_results.py
      - outputs/models/
    metrics:
      - outputs/results/summary.json:
          cache: false