name: halueval_qa
path: data/HaluEval/qa_data.json
cls_path: src.data.halueval.HaluEvalQADataset

splits: null
task_types: null
max_samples: null

# 特征提取时使用的数据分割 (train/test)
split_name: train

max_answer_tokens: 256
target_column_name: hallucinated_answer
test_split_name: null
