name: truthfulqa
path: null
subset: generation
cls_path: src.data.truthfulqa.TruthfulQADataset

splits:
  - validation
task_types: null
max_samples: null

# 特征提取时使用的数据分割 (train/test)
split_name: train

max_answer_tokens: 128
target_column_name: answer
test_split_name: validation
