# =============================================================================
# DVC Pipeline for Hallucination Detection
# =============================================================================
# 目录结构: {base}/{dataset}/{model}/seed_{seed}/{task_type}/{method}/{level}/
# 
# 流程顺序:
#   1. split_dataset - 分割数据集
#   2. generate_activations - 提取训练集特征
#   3. generate_activations_test - 提取测试集特征
#   4. train_probe - 训练探测器 (按 method × level 组合)
#   5. evaluate - 评估 (按 method × level 组合)
#   6. aggregate - 汇总结果
# =============================================================================

vars:
  - params.yaml

stages:
  # ===========================================================================
  # Stage 1: 数据分割
  # ===========================================================================
  split_dataset:
    cmd: python scripts/split_dataset.py
    deps:
      - scripts/split_dataset.py
      - config/dataset/
    params:
      - datasets
      - split
      - seed
    outs:
      - outputs/splits/:
          persist: true

  # ===========================================================================
  # Stage 2a: 训练集特征提取
  # ===========================================================================
  generate_activations: 
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
    cmd: >-
      CUDA_VISIBLE_DEVICES=${cuda_devices}
      python scripts/generate_activations.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      dataset.split_name=train
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      features.mode=${features.mode}
      features.max_length=${features.max_length}
      features.batch_size=${features.batch_size}
      seed=${seed}
      methods=[${methods_str}]
      allow_full_attention=${allow_full_attention}
    deps:
      - scripts/generate_activations.py
      - src/
      - config/
      - utils/
      - outputs/splits/
    params:
      - features.mode
      - features.max_length
      - features.batch_size
      - seed
      - methods
    outs:
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/: 
          persist: true

  # ===========================================================================
  # Stage 2b: 测试集特征提取
  # ===========================================================================
  generate_activations_test: 
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
    cmd: >-
      CUDA_VISIBLE_DEVICES=${cuda_devices}
      python scripts/generate_activations.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      dataset.split_name=test
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      features.mode=${features.mode}
      features.max_length=${features.max_length}
      features.batch_size=${features.batch_size}
      seed=${seed}
      methods=[${methods_str}]
      allow_full_attention=${allow_full_attention}
    deps:
      - scripts/generate_activations.py
      - src/
      - config/
      - utils/
      - outputs/splits/
    params:
      - features.mode
      - features.max_length
      - features.batch_size
      - seed
      - methods
    outs:
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}_test/: 
          persist: true

  # ===========================================================================
  # Stage 3: 训练探测器
  # ===========================================================================
  # ⚠️ 变更: 增加了 level 矩阵参数，输出路径改为 {method}/{level}/
  train_probe: 
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
      method: ${methods}
      level: ${levels}
    cmd: >-
      python scripts/train_probe.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      method=${item.method}
      method.level=${item.level}
      seed=${seed}
    deps:
      - scripts/train_probe.py
      - src/
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/
      - outputs/splits/
    params:
      - seed
      - cv_folds
    outs:
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/${item.level}/: 
          persist: true

  # ===========================================================================
  # Stage 4: 评估
  # ===========================================================================
  # ⚠️ 变更: 增加了 level 矩阵参数，路径与 train_probe 保持一致
  evaluate:
    matrix: 
      dataset: ${datasets}
      task_type: ${task_types}
      model: ${models}
      method: ${methods}
      level: ${levels}
    cmd: >-
      python scripts/evaluate.py
      dataset.name=${item.dataset.name}
      dataset.task_type=${item.task_type}
      model=${item.model.name}
      model.short_name=${item.model.short_name}
      method=${item.method}
      method.level=${item.level}
      seed=${seed}
    deps: 
      - scripts/evaluate.py
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/${item.level}/
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/
      - outputs/features/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}_test/
      - outputs/splits/
    params:
      - seed
    metrics:
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/${item.level}/eval_results.json:
          cache: false
    plots:
      - outputs/models/${item.dataset.name}/${item.model.short_name}/seed_${seed}/${item.task_type}/${item.method}/${item.level}/roc_curve.json:
          cache: false
          x: fpr
          y: tpr

  # ===========================================================================
  # Stage 5: 汇总结果
  # ===========================================================================
  aggregate:
    cmd: python scripts/aggregate_results.py
    deps:
      - scripts/aggregate_results.py
      - outputs/models/
    metrics:
      - outputs/results/summary.json:
          cache: false
