# =============================================================================
# DVC Parameters - 支持按任务类型分别训练
# =============================================================================
# 修改这些值后运行 `dvc repro` 即可重新运行整个流水线
# 支持矩阵交叉：所有 datasets × task_types × models × methods 的组合都会被执行
#
# 目录结构:
#   features: outputs/features/{dataset}/{model}/seed_{seed}/{task_type}/
#   models:   outputs/models/{dataset}/{model}/seed_{seed}/{task_type}/{method}/probe/
# =============================================================================

# -----------------------------------------------------------------------------
# 数据集配置
# -----------------------------------------------------------------------------
datasets:
  - name: ragtruth

# -----------------------------------------------------------------------------
# 任务类型配置 (RAGTruth 有 3 种任务类型)
# -----------------------------------------------------------------------------
# 每种任务类型会分别提取特征、训练模型、评估
# 最终汇总时会输出每个任务类型的 AUROC 和 AUPRC
task_types:
  - QA
  - Summary
  - Data2txt

# -----------------------------------------------------------------------------
# 模型配置
# -----------------------------------------------------------------------------
# short_name 必须与脚本输出的目录名一致
# models: 
#   - name: mistral_7b
#     short_name: Mistral-7B-Instruct-v0.3
models: 
  - name: llama2_7b_chat             
    short_name: Llama-2-7b-chat-hf

# -----------------------------------------------------------------------------
# 检测方法配置
# -----------------------------------------------------------------------------
# 特征提取会自动计算所有方法的特征需求并集
# 确保一次提取可以满足所有方法的需要
methods: 
  - lapeigvals
  - lookback_lens
  - haloscope
  - hsdmvaf
  - semantic_entropy_probes
  - tsv
  - hypergraph

# methods_str: 用于 DVC 命令行传递的字符串格式
# DVC 不支持直接在 cmd 中展开列表，需要预先格式化
methods_str: "lapeigvals,lookback_lens,haloscope,hsdmvaf,hypergraph,semantic_entropy_probes,tsv"

# -----------------------------------------------------------------------------
# 特征提取配置 (内存优化)
# -----------------------------------------------------------------------------
# ⚠️ 这是特征提取的主要配置源
# Hydra会将这些值合并到 features 配置中
features: 
  mode: teacher_forcing
  attention_layers: all
  # ⚠️ max_length 是token数量限制，不是字符数

  max_length: 10000
  store_mode: incremental
  batch_size: 4

# -----------------------------------------------------------------------------
# GPU配置
# -----------------------------------------------------------------------------
cuda_devices: "0,1"  # 多GPU用逗号分隔

# -----------------------------------------------------------------------------
# 完整注意力控制
# -----------------------------------------------------------------------------
# hsdmvaf 方法需要 full_attention 以获得最佳效果
# 设为 true 会显著增加内存使用
allow_full_attention: true

# -----------------------------------------------------------------------------
# 数据分割配置
# -----------------------------------------------------------------------------
split:
  test_ratio: 0.1
  random_seed: 42
  stratify: true
  # 注意：不再支持删除原始数据
  # 原始数据将保持不变，分割结果保存在 outputs/splits/

# -----------------------------------------------------------------------------
# 训练与评估配置
# -----------------------------------------------------------------------------
seed: 42
cv_folds: 5

# 级别配置（统一字段，替代原 classification_levels）
# 支持 sample（样本级）或 token（token级）
levels:
  - sample

# 评估矩阵：定义训练任务和评估任务的组合
# 如果不指定，默认为同任务评估（train_task == eval_task）
# 跨任务评估示例：
# eval_matrix:
#   - train_task: QA
#     eval_task: Summary
#   - train_task: Summary
#     eval_task: Data2txt

# -----------------------------------------------------------------------------
# 输出目录
# -----------------------------------------------------------------------------
features_dir: outputs/features
models_dir: outputs/models
results_dir: outputs/results
