# =============================================================================
# DVC Parameters - 支持按任务类型和级别分别训练
# =============================================================================
# 修改这些值后运行 `dvc repro` 即可重新运行整个流水线
#
# ⚠️ 重要变更 (v2.0):
# - 移除了独立的 `levels` 参数
# - 使用 `method_levels` 定义每个方法支持的 (method, level) 组合
# - 这样确保只训练/评估方法实际支持的级别
#
# 目录结构:
#   features: outputs/features/{dataset}/{model}/seed_{seed}/{task_type}/
#   models:   outputs/models/{dataset}/{model}/seed_{seed}/{task_type}/{method}/{level}/
# =============================================================================

# -----------------------------------------------------------------------------
# 数据集配置
# -----------------------------------------------------------------------------
datasets:
  - name: ragtruth

# -----------------------------------------------------------------------------
# 任务类型配置 (RAGTruth 有 3 种任务类型)
# -----------------------------------------------------------------------------
task_types:
  - QA
  - Summary
  - Data2txt

# -----------------------------------------------------------------------------
# 模型配置
# -----------------------------------------------------------------------------
models: 
  - name: llama2_7b_chat             
    short_name: Llama-2-7b-chat-hf

# -----------------------------------------------------------------------------
# 方法-级别组合配置 (⚠️ 核心变更)
# -----------------------------------------------------------------------------
# 每个条目定义一个有效的 (method, level) 组合
# 这些组合来源于各方法配置文件中的 level 字段:
#   - level: sample  → 只添加 sample 组合
#   - level: token   → 只添加 token 组合
#   - level: both    → 添加 sample 和 token 两个组合
#
# 参考各方法的 level 配置:
#   - lapeigvals: sample
#   - lookback_lens: both
#   - haloscope: sample
#   - hsdmvaf: sample
#   - semantic_entropy_probes: sample
#   - tsv: (无配置，默认 sample)
#   - hypergraph: both
#   - act: sample
#   - token_entropy: sample
# -----------------------------------------------------------------------------
method_levels:
  # act - level: sample
  # - method: act
  #   level: sample
  
  # lapeigvals - level: sample
  - method: lapeigvals
    level: sample
  
  # lookback_lens - level: both
  - method: lookback_lens
    level: sample
  - method: lookback_lens
    level: token
  
  # haloscope - level: sample
  - method: haloscope
    level: sample
  
  # hsdmvaf - level: sample
  - method: hsdmvaf
    level: sample
  
  # semantic_entropy_probes - level: sample
  - method: semantic_entropy_probes
    level: sample
  
  # token_entropy - level: sample
  - method: token_entropy
    level: sample
  
  # tsv - 默认 sample
  - method: tsv
    level: sample
  
  # hypergraph - level: both
  - method: hypergraph
    level: sample
  - method: hypergraph
    level: token

# -----------------------------------------------------------------------------
# methods 列表 (用于特征提取)
# -----------------------------------------------------------------------------
# 特征提取只需要方法名称列表，会自动计算所有方法的特征需求并集
methods: 
  - lapeigvals
  - lookback_lens
  - haloscope
  - hsdmvaf
  - semantic_entropy_probes
  - token_entropy
  - tsv
  - hypergraph

# methods_str: 用于 DVC 命令行传递的字符串格式
methods_str: "lapeigvals,lookback_lens,haloscope,hsdmvaf,hypergraph,semantic_entropy_probes,token_entropy,tsv"

# -----------------------------------------------------------------------------
# 特征提取配置 (内存优化)
# -----------------------------------------------------------------------------
features: 
  mode: teacher_forcing
  attention_layers: all
  max_length: 10000
  store_mode: incremental
  batch_size: 4

# -----------------------------------------------------------------------------
# GPU配置
# -----------------------------------------------------------------------------
cuda_devices: "0,1"

# -----------------------------------------------------------------------------
# 完整注意力控制
# -----------------------------------------------------------------------------
allow_full_attention: true

# -----------------------------------------------------------------------------
# 数据分割配置
# -----------------------------------------------------------------------------
split:
  test_ratio: 0.1
  random_seed: 42
  stratify: true

# -----------------------------------------------------------------------------
# 训练与评估配置
# -----------------------------------------------------------------------------
seed: 42
cv_folds: 5

# -----------------------------------------------------------------------------
# 输出目录
# -----------------------------------------------------------------------------
features_dir: outputs/features
models_dir: outputs/models
results_dir: outputs/results
